package com.example.nepalikeyboard

object charMapping{
    val englishCharacterMap=mapOf(
            "a" to "अ",
            "aa" to "आ",
            "i" to "इ",
            "ii" to "ई",
            "u" to "उ",
            "uu" to "ऊ",
            "e" to "ए",
            "ai" to "ऐ",
            "o" to "ओ",
            "au" to "औ",
            "ri" to "ऋ",
            "ka" to "क",
            "kha" to "ख",
            "ga" to "ग",
            "gha" to "घ",
            "Nga" to "ङ",
            "cha" to "च",
            "chha" to "छ",
            "ja" to "ज",
            "jha" to "झ",
            "Nja" to "ञ",
            "Ta" to "ट",
            "Tha" to "ठ",
            "Da" to "ड",
            "Dha" to "ढ",
            "Na" to "ण",
            "ta" to "त",
            "tha" to "थ",
            "da" to "द",
            "dha" to "ध",
            "na" to "न",
            "pa" to "प",
            "pha" to "फ",
            "fa" to "फ",
            "ba" to "ब",
            "bha" to "भ",
            "ma" to "म",
            "ya" to "य",
            "ra" to "र",
            "la" to "ल",
            "wa" to "व",
            "va" to "व",
            "sha" to "श",
            "Sha" to "ष",
            "sa" to "स",
            "ha" to "ह",
            "kSha" to "क्ष",
            "tra" to "त्र",
            "Gya" to "ज्ञ"
    )
}
